
(function(page){
    links <- list(c("/index.html", "Home"),
                  c("/about.html", "About"),
                  c("/research.html", "Research"),
                  c("/papers.html", "Papers"),
                  c("https://github.com/DASpringate", "Github"))
    webdoc("html5",
           html_head(title = "David Springate's blog",
               '<meta charset="utf-8"><meta content="width=device-width, initiali-scale=1.0, user-scalable=yes" name="viewport">',
               m("div.container-fluid well",
                 m("h1", "What is this?"),
                 m("p", "David Springate's personal blog on programming, data, informatics, biostatistics and evolution")),
               m("div.subnav",
                 unordered.list(lapply(links, function(x) link.to(x[1], x[2])),
                                  list.opts = list(class="nav nav-pills"))),
               '<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css">',
               '<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css">',
               '<link href="/css/smartphone.css" media="only screen and (max-device-width:480px)" rel="stylesheet" type="text/css">'),
           html_body(m("div.container-fluid",
                  m("div.row-fluid",
                    m("div.span1"),
                    m("div.span9", page),
                    m("div.span2", 
                      m("h3", "Tags"),
                      html.taglist(site))),
                  m("div.span12",
                    m("div.span2"),
                    m("div.span8",
                      m("footer.footer",
                        m("p.right back_to_top",
                          link.to("#", "&uArr; Page Top")),
                        m("p",
                          link.to("http://twitter.com/datajujitsu", "@datajujitsu"),
                          "&nbsp; 2013")))))))
})(page)